### ISSUE TITLE
Spacewalk Client module

### ISSUE THREAD

**Issue by ghost** [CommanderK5/puppet-spacewalk#2]
To whom it may concern,

After including the client module. how do you configure the client to talk to the server? are the configuration done manually?

**Comment by CommanderK5** [comment]
Hi,
Client configuration is not supported in this module, spacewalk::repo::client class that you are probably talking about is just a spacewalk client yum repository, if you want to setup your clients you can use [puppet-rhnreg_ks](https://github.com/strider/puppet-rhnreg_ks).

**Comment by ghost** [comment]
Thank you
